//
//  PEGBaseRequestAFN.h
//  PEG
//
//  Created by Pierre Marty on 19/02/2014.
//  Copyright (c) 2014 spir. All rights reserved.
//

#if USE_AFNetworking

#import "AFHTTPRequestOperation.h"
#import "SPIRRequestProtocol.h"

typedef enum {
    ADXNotReachableErrorType = 100,
	ADXInvalidXMLErrorType = 200,
	ADXSoapFaultErrorType = 300,
	ADXEmptyResponseErrorType = 400
} ADXNetworkErrorType;

// The error domain that all errors generated by ADXBaseRequest use
extern NSString* const ADXNetworkRequestErrorDomain;

@class SPIRMessage, PEGRequestFormatter;

@interface PEGBaseRequest : AFHTTPRequestOperation <SPIRRequestProtocol>
{
}

@property (nonatomic, readonly) NSMutableArray *sapMessages;
@property (weak, nonatomic, readonly) SPIRMessage *mainMessage;
@property (nonatomic, readonly) BOOL hasMessages;
@property (weak, nonatomic, readonly) NSString *errorTitle;
@property (weak, nonatomic, readonly) NSString *errorMessage;
@property (nonatomic, readonly) PEGRequestFormatter *requestFormatter;


- (void)setSpecificTimeOutSeconds:(double)timeOut;

#pragma mark - ASIHTTPRequest emulation

@property (nonatomic, strong) NSMutableData * postBody;

+ (PEGBaseRequest *)requestWithURL:(NSURL *)URL;
- (id)initWithURL:(NSURL *)URL;

- (void)setSuccessBlock:(void (^)(void))block;
- (void)setFailedBlock:(void (^)(void))block;

- (void)startAsynchronous;
- (void)startSynchronous;
- (void)addBasicAuthenticationHeaderWithUsername:(NSString *)theUsername andPassword:(NSString *)thePassword;

#pragma mark -

- (void)configureRequestInJsonCompressedFormat;

- (id)processResponseWithJsonKeyPath;
- (UIImage*)processResponseImage;


#pragma mark - cache

+ (BOOL)hasCache;
+ (void)clearCache;

- (void)saveRequestToCache;
// - (void)restoreRequestFromCache;



@end


#endif
