//
//  PEGBaseRequest.h
//  adrexo
//
//  Created by Frédéric JOUANNAUD on 28/06/12.
//  Copyright (c) 2012 SQLI. All rights reserved.
//


#import "ASIHTTPRequest.h"
#import "SPIRRequestProtocol.h"

typedef enum {
    ADXNotReachableErrorType = 100,
	ADXInvalidXMLErrorType = 200,
	ADXSoapFaultErrorType = 300,
	ADXEmptyResponseErrorType = 400
} ADXNetworkErrorType;

// The error domain that all errors generated by ADXBaseRequest use
extern NSString* const ADXNetworkRequestErrorDomain;

@class SPIRMessage, PEGRequestFormatter;

@interface PEGBaseRequest : ASIHTTPRequest <SPIRRequestProtocol>
{
	NSMutableArray			*sapMessages;
	PEGRequestFormatter		*requestFormatter;
}

@property (nonatomic, readonly) NSMutableArray *sapMessages;
@property (weak, nonatomic, readonly) SPIRMessage *mainMessage;
@property (nonatomic, readonly) BOOL hasMessages;
@property (weak, nonatomic, readonly) NSString *errorTitle;
@property (weak, nonatomic, readonly) NSString *errorMessage;
@property (nonatomic, readonly) PEGRequestFormatter *requestFormatter;


-(void)setSpecificTimeOutSeconds:(double)p_TimeOut;
- (id)processResponseWithJsonKeyPath;
- (id)processResponseWithKeyPath:(NSString *)soapResponseTagName;
- (UIImage*)processResponseImage;
- (BOOL)hasWarningMessages;
- (BOOL)hasErrorMessages;
+ (id)defaultRequest;
+ (NSDictionary *)standardParameters;
+ (NSDictionary *)standardFormatters;

+ (BOOL)hasCache;
+ (void)clearCache;

- (void)saveRequestToCache;
- (void)restoreRequestFromCache;

- (void)configureRequestInJsonCompressedFormat;

@end

